### ISSUE TITLE
setPreserveTypes() does not work with fetchObjects()

### ISSUE THREAD

**Issue by leeoniya** [rkrx/php-mysql-query-builder#3]
may also be useful to have a global `preserveTypes` default that can be set on the database instance (or a shared `RunnableSelect::setPreserveTypes()`) rather than having to set it per statement.

`JSON_NUMERIC_CHECK` may take care of converting returned floats/decimal/numerics for JSON/REST apis, but it's good to have the real types available sooner, too.

**Comment by rkrx** [comment]
Based on your suggestion, i've added some parameters to specify the desired behaviour: 
[initialization.md](https://github.com/rkrx/php-mysql-query-builder/blob/master/doc/initialization.md)
[releases/tag/0.1.47](https://github.com/rkrx/php-mysql-query-builder/releases/tag/0.1.47)

**Comment by leeoniya** [comment]
that works, thanks!

**Comment by rkrx** [comment]
You're welcome
